networks:
  journal:
    internal: true
  proxy:

services:
  journal:
    build: https://github.com/devMaFi/journal.git#bugfix-ruby_upgrade
    image: travel-journal
    volumes:
      - $PWD:/app:rw
    environment:
      - RAILS_ENV=production
      - SITE_DOMAIN='mydomain.ltd'
      - DATABASE_URL=postgres://journal:RePLAcEpAsS@journal-db/journal_db
      - CIPHER_KEY='changeit' # openssl rand -base64 32
      - SHARING_TOKEN_CIPHER_IV='change t' # openssl rand -base64 16
      - SECRET_KEY_BASE='changeit' # random alphanumerical
    ports:
      - 3002:3000
    networks:
      - proxy
      - journal
    restart: unless-stopped

  journal-db:
    image: postgres:alpine
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "journal"]
    environment:
      - POSTGRES_DB=journal_db
      - POSTGRES_USER=journal
      - POSTGRES_PASSWORD=RePLAcEpAsS
    volumes:
      - $PWD/postgres:/var/lib/postgresql/data:rw
    networks:
      - journal
    restart: unless-stopped
